version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vo-donate
      - NODE_ENV=development
      - TZ=Asia/Seoul
      - PORT=3000
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
